---
- name: Ejecutar script SQL usando SQL*Plus
  shell: sqlplus -S {{ oracle_user }}/{{ oracle_password }}@localhost:{{ oracle_port }}/{{ oracle_database }} @{{ script_sql_path }}
  environment: 
    ORACLE_HOME: "{{varible_home}}"
    PATH: "{{path_bin}}"
    LD_LIBRARY_PATH: "{{ ld_path }}"
  register: sqlplus_output
  
- name: Mostrar salida de SQL*Plus
  debug:
    var: sqlplus_output.stdout_lines