- name: Ejecucion de script
  hosts: "{{server_oracle}}"
  become: true
  tasks:
    - name: Ejecucion de script
      include_role:
        name: roles/EjecucionS
  become_method: su 
  become_user: guate
